### ISSUE TITLE
Themes without screenshots should not show the thumbnail

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/website#139]
On the themes page, most themes have a screenshot available. If it doesn't, the website doesn't handle it very gracefully:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/1443710/99290503-5ecace00-280c-11eb-8888-24731b366b1d.png">

There is a corresponding error logged, looking for static/images/themes/darkmod-neo.png.

We should first check whether the screenshot exists, and respond a bit better if it doesn't.

**Comment by vimalMK** [comment]
I can have a look at this, if its still need to be fixed?

**Comment by ibennetch** [comment]
@vimalMK yes, this still needs to be improved.

**Comment by vimalMK** [comment]
@ibennetch Cool! will do some insights on this. Thank you. :)

**Comment by vimalMK** [comment]
@ibennetch  Need some clarification. is the master branch the latest code base for the website https://www.phpmyadmin.net/

Because I see some difference in the UI when trying to run locally. please advise.

**Comment by ibennetch** [comment]
Yes, it should be running from master; what differences are you seeing?

**Comment by vimalMK** [comment]
@ibennetch 

My local:
![image](https://user-images.githubusercontent.com/35750792/197928512-90ab96c1-f202-44f9-92aa-6c838a79cb76.png)
![image](https://user-images.githubusercontent.com/35750792/197928994-a3469e48-51bc-43f8-9a1a-ea913a379d95.png)

Original website:
![image](https://user-images.githubusercontent.com/35750792/197928549-91351cd0-bb05-42d1-84dd-44e560c42ec6.png)
![image](https://user-images.githubusercontent.com/35750792/197928955-f89650a1-838e-465d-ae61-a20cc44a71c1.png)

**Comment by vimalMK** [comment]
PR #153 . Happy coding.
