### ISSUE TITLE
phpMyAdmin Demos are broken

### ISSUE THREAD

**Issue by matzex** [phpmyadmin/website#148]
Hello,

currently the linked demo versions of the phpMyAdmin Software on this [website ](https://www.phpmyadmin.net/try/) are all broken. The error message is the same for all versions:

> `phpMyAdmin - Error
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.
session_write_close(): write failed: No space left on device (28)
session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/var/lib/php/sessions)`

Would be great if someone could fix this.
Thank you very much for the good work!
Matthias

**Comment by ibennetch** [comment]
Thanks for your report. I'll be busy this morning but we will check this out when we can.

**Comment by williamdes** [comment]
Should be fixed now :)
