### ISSUE TITLE
Misaligned close button in modal on downloads page

### ISSUE THREAD

**Issue by winstonDeGreef** [phpmyadmin/website#150]
In the modal that opens on the phpymadmin download page when clicking on a download link, the close button is misaligned.

browser info: `Version 98.0.4758.102 (Official Build) (64-bit)` running on ubuntu

![Frame 1](https://user-images.githubusercontent.com/71840364/155850117-da4bdf4e-c80d-41e6-b066-dd73b5feaa75.png)

**Comment by williamdes** [comment]
Hi @mauriciofauth 
Could you please have a look ?

**Comment by mauriciofauth** [comment]
> Could you please have a look ?

Sure thing.

**Comment by vimalMK** [comment]
Hi @williamdes  @MauricioFauth  Can I have a look at it?

**Comment by ibennetch** [comment]
@vimalMK yes, that would be great.

**Comment by ibennetch** [comment]
@vimalMK that styling and spacing looks good. I think a close button belongs on the right side, though, could you move it as part of your fix?

**Comment by winstonDeGreef** [comment]
That button feels as if it is too close to the top. (Also, float: right or float: lef in css makes the browser handle the flow of text around the element)

**Comment by vimalMK** [comment]
> @vimalMK that styling and spacing looks good. I think a close button belongs on the right side, though, could you move it as part of your fix?

I should be able to do that. 

> That button feels as if it is too close to the top. (Also, float: right or float: lef in css makes the browser handle the flow of text around the element)

Using float make sense and might as well use some padding around button for position.

Thanks you. Will get to the PR soon.

**Comment by vimalMK** [comment]
PR added with changes #152

**Comment by williamdes** [comment]
It should be okay now
