### ISSUE TITLE
Failed to read configuration file error with "manage.py fetch_versions"

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/website#160]
Since the server upgrade to Debian Bookworm, the following error occurs when trying to run `website/manage.py fetch_versions`
```
Failed to read the version configuration file.
Check the status of https://demo.phpmyadmin.net/versions.ini
```

**Comment by ibennetch** [comment]
Running `curl https://demo.phpmyadmin.net/versions.ini` from the server seems to give expected output, so it's likely not a problem with the actual versions.ini file.

**Comment by williamdes** [comment]
It makes me think it could be some python issue
The planet command is also failing, local exec works fine too
