### ISSUE TITLE
Daily snapshots aren't generated since 2023-11-28

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/website#165]
This is another issue, not related to #164. Daily snapshots aren't generated since 2023-11-28.

See https://www.phpmyadmin.net/downloads/.

**Comment by ibennetch** [comment]
> scripts/website/daily-snapshots: 33: ./scripts/create-release.sh: not found

Caused by https://github.com/phpmyadmin/phpmyadmin/pull/18798
