### ISSUE TITLE
Download links should escape plus sign

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/website#166]
When generating the links to download a snapshot, such as file `phpMyAdmin-6.0+snapshot-all-languages.zip`, the plus sign should technically be URL encoded to `%2b`.

This isn't usually a problem that I've seen, but there is something going on with our CDN that causes downloads to fail verification. Our CDN provider is looking at whether there is something they should do to fix it, but according to (my understanding of) the standards we should also encode the plus sign here.

**Comment by ibennetch** [comment]
This is directly related to #164.

**Comment by ibennetch** [comment]
I may be mistaken on this, according to https://stackoverflow.com/a/2678602/2385479 it appears to me the plus sign is literal in a URL except when part of a query string. So I think our code and URL is technically correct.

We are still discussing it with the CDN provider.

**Comment by liviuconcioiu** [comment]
According to RFC1738, plus sign is allowed in the URL - https://datatracker.ietf.org/doc/html/rfc1738#section-2.1.
According to RFC1630, plus sign should be encoded if it's in the query string - https://datatracker.ietf.org/doc/html/rfc1630

So, clearly the issue is on their side.

**Comment by MauricioFauth** [comment]
@ibennetch Could we encoded the URL to encode the plus sign to `%2B` as a temporary fix?

**Comment by williamdes** [comment]
> So, clearly the issue is on their side.

Thank you for the RFC links.

I sent an email expressing our dissatisfaction about they reply.

**Comment by williamdes** [comment]
> @ibennetch Could we encoded the URL to encode the plus sign to `%2B` as a temporary fix?

Done

**Comment by williamdes** [comment]
You can revert your fixes, URLs work now 🎉 
Ref: https://github.com/phpmyadmin/website/issues/164#issuecomment-2573073388
