### ISSUE TITLE
phpMyAdmin demo server issues

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/website#172]
There are a few issues on the demo server:

- [x] `phpMyAdmin Demo Server: Git information missing!` - probably `revision-info.php` doesn't exist.
- [x] `Error while working with template cache: Unable to create the cache directory (/home/demo/.pma-demo/master-config/app/cache/twig/eb).` - it happens because of the `twig` folder present in the release
- [x] `Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "PhpMyAdmin\Controllers\Database\OperationsController".` - probably an older cache file that isn't removed when the snapshot is created, same like `twig`
- [x] There's a 1 day delay between the snapshot generated and snapshot pulled from CDN.

https://demo.phpmyadmin.net/master-config/public/

![3](https://github.com/phpmyadmin/website/assets/25424343/18756df3-1fd0-42e0-9402-240d64df4a58)

https://demo.phpmyadmin.net/master-config/public/index.php?route=/database/operations&db=mysql

![4](https://github.com/phpmyadmin/website/assets/25424343/9009e45e-0684-473e-863b-b3e3acca73b1)

![version](https://github.com/phpmyadmin/website/assets/25424343/e160f201-30c8-4ad0-ad5a-6fc6c2a4d32c)

**Comment by ibennetch** [comment]
Thanks, I’ll look at some of these.

**Comment by liviuconcioiu** [comment]
I've figured out why `Error while working with template cache: Unable to write in the cache directory` message is given.

If you download the 6.0.0-dev snapshots in any format, https://files.phpmyadmin.net/snapshots/phpMyAdmin-6.0%2Bsnapshot-english.zip, the archives contain the `twig` folder, which isn't supposed to do that.

![twig](https://github.com/phpmyadmin/website/assets/25424343/4c14d96a-fc33-4b76-a7a5-119e1ae81d8c)

/cc @MauricioFauth

**Comment by williamdes** [comment]
> the archives contain the twig folder, which isn't supposed to do that.

Well, on 6.0 the twig cache is supposed to be shipped in the folder of your screenshot. But that said it should not write to this folder is cache is not hit. I already complained about this but can not find on what issue.
See: https://github.com/phpmyadmin/phpmyadmin/issues/14604 and https://github.com/phpmyadmin/phpmyadmin/pull/18832

**Comment by liviuconcioiu** [comment]
@williamdes can you confim the 4th issue? Just found it now.

**Comment by williamdes** [comment]
> @williamdes can you confim the 4th issue? Just found it now.

I am unsure about this since we update and purge the CDN each time the snapshot is updated.

**Comment by liviuconcioiu** [comment]
Closing this one. Git info seems to be fixed. Probably by the latest commit https://github.com/phpmyadmin/scripts/commit/affad722b566bffc62bb1dd2fb25f27ad6668944
