### ISSUE TITLE
Demo server versions not updating to the latest commit

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/website#179]
I see that the demo server no longer updates the versions to the latest commit, both `QA_5_2` and `master`.

**Comment by williamdes** [comment]
Done:
- https://github.com/phpmyadmin/scripts/commit/d8c97ad84a555655af933e20b90c41254de54a47
- 5e16f70fa59b78302d9f882346acd45c2f92e61e

It works fine, but I am unsatisfied not to have the git commit information like before when it had a git folder

**Comment by liviuconcioiu** [comment]
I agree! It was handy, since it could be clicked and see changes. I also think that we should add a link to the commit, if git folder is missing. It's usefull especially on the downloaded snapshots.

**Comment by williamdes** [comment]
> I agree! It was handy, since it could be clicked and see changes. I also think that we should add a link to the commit, if git folder is missing. It's usefull especially on the downloaded snapshots.

And we already have the info in `revision-info.php`

**Comment by williamdes** [comment]
All done, it feels so good to be back working on phpMyAdmin !

**Comment by liviuconcioiu** [comment]
@williamdes could you look again into this when you have free time? Something is not working as expected on `master`.

`QA_5_2`, works, but `master,` doesn't:

`Version information: 6.0.0-dev+20241219.8e721911f0`

**Comment by williamdes** [comment]
> @williamdes could you look again into this when you have free time? Something is not working as expected on `master`.
> 
> `QA_5_2`, works, but `master,` doesn't:
> 
> `Version information: 6.0.0-dev+20241219.8e721911f0`

I have ` 6.0.0-dev+20241226.a183670555`
On https://demo.phpmyadmin.net/master/public/index.php?route=/
I looks up to date and on the mailing list for crons it seems to update quite often

**Comment by liviuconcioiu** [comment]
Then, something was buggy, maybe network issue, because there were plenty of merges betwwen those commits, and demo server wasn't up to date. Now I see it works. I'll let you know if does happen again!

**Comment by liviuconcioiu** [comment]
@williamdes I know why. If you go to demo server from website, you are redirected to `master-config`. This is the one that is broken.

https://demo.phpmyadmin.net/master-config/public/

**Comment by williamdes** [comment]
> @williamdes I know why. If you go to demo server from website, you are redirected to `master-config`. This is the one that is broken.
> 
> https://demo.phpmyadmin.net/master-config/public/

Okay, thanks. I will check the script
