### ISSUE TITLE
Daily Snapshots Cannot Be Downloaded

### ISSUE THREAD

**Issue by jweaver0312** [phpmyadmin/website#180]
As an example when going to https://files.phpmyadmin.net/snapshots/phpMyAdmin-6.0%2bsnapshot-english.tar.gz

404 Not Found
Code: NoSuchKey
BucketName: download-object
RequestId: tx000003e0388153ba9199f-00670599b3-69b37d9-prg
HostId: 69b37d9-prg-eu-1

**Comment by williamdes** [comment]
Duplicate of #166

**Comment by williamdes** [comment]
The link you provided works fine for me

**Comment by jweaver0312** [comment]
Not a duplicate since as explained I already accounted for escaping the + sign by using %2B

Still does not work on my end and says Not Found

**Comment by williamdes** [comment]
One question: what software do you use to download it ?

`curl -v https://files.phpmyadmin.net/snapshots/phpMyAdmin-6.0%2bsnapshot-english.tar.gz` -> 200

**Comment by jweaver0312** [comment]
I am generally using a web browser to download such as Chrome, Firefox, but do use curl command line when I'm having issue grabbing it that way.

**Comment by williamdes** [comment]
> I am generally using a web browser to download such as Chrome, Firefox, but do use curl command line when I'm having issue grabbing it that way.

I fixed the website URLs to download the files, it should work better if you are using a browser

**Comment by williamdes** [comment]
Is your issue fixed?

**Comment by jweaver0312** [comment]
My apologies, I’ll check again right now and I’ll download a snapshot now and then download the next one that should be available later today in my time zone as the 12/7 snapshot would generally release later tonight in my time zone.

**Comment by jweaver0312** [comment]
Yes it seems it is fixed.

**Comment by williamdes** [comment]
You can revert your fix, URLs work now 🎉 
Ref: https://github.com/phpmyadmin/website/issues/164#issuecomment-2573073388
