### ISSUE TITLE
Missing Redirect to HTTPS from HTTP

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/website#32]
As report by Emanuel Bronshtein,

visiting over HTTP the following websites will not redirect to HTTPS:
- [x] http://admin.phpmyadmin.net
- [x] http://develdocs.phpmyadmin.net
- [x] http://reports.phpmyadmin.net/
- [x] http://planet.phpmyadmin.net/
- [x] http://klutz.phpmyadmin.net
- [x] http://ci.phpmyadmin.net/
- [x] http://hooks.phpmyadmin.net

**Comment by nijel** [comment]
* For reports this is intentional setup to allow old clients to submit data.
* For hooks we first needs to check if we're not using http URL somewhere.
* For develdocs it's something what needs to be done at the CDN side (same issue is for www.phpmyadmin.net).

**Comment by nijel** [comment]
I've reviewed all hooks on GitHub and switched them to https, so hopefully we're safe to fully switch to https there.

**Comment by nijel** [comment]
I've just changed CDN setup on all hosts to make it consistent:

* Redirect to HTTPS
* Use letsencrypt certificates
* Use HTTPS for backend connection

**Comment by emanuelb** [comment]
For reports consider a redirect that black-list submit end-points (will redirect to HTTPS if the request-uri isn't /incidents/create) or redirect on non POST requests (as submissions done over POST)

**Comment by nijel** [comment]
Thats indeed an option, thanks for suggestion!

**Comment by nijel** [comment]
Now done for reports as well.
