### ISSUE TITLE
Exposing Apache Version

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/website#39]
As reported by Emanuel Bronshtein,

https://lists.phpmyadmin.net/icons/apache_pb2.png
https://lists.phpmyadmin.net/icons/

Apache/2.4.10 (Debian) Server at lists.phpmyadmin.net Port 80

fix:
    1. remove icons folder.
    2. add in apache configuration file:

```
    ServerSignature Off
    ServerTokens Prod
```

**Comment by nijel** [comment]
Fixed.
