### ISSUE TITLE
Invalid certificate (domain mismatch) for mail.phpmyadmin.net

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/website#41]
Visit:
https://mail.phpmyadmin.net/
Result: (SSL Error)
```
mail.phpmyadmin.net uses an invalid security certificate.
The certificate is only valid for lists.phpmyadmin.net
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```
fix:
use valid certificate for mail.phpmyadmin.net

**Comment by nijel** [comment]
Fixed, the certificate has been already issued, just the web server configuration was wrong. Thanks for noticing this.
