### ISSUE TITLE
incorrect commits in security advisories

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/website#45]
in:
https://www.phpmyadmin.net/security/PMASA-2016-58/
The second commit "Use hash_equals for checking username" is not related to the issue

in:
https://www.phpmyadmin.net/security/PMASA-2016-42/
the commit https://github.com/phpmyadmin/phpmyadmin/commit/7ef96c5 return 404

in:
https://www.phpmyadmin.net/security/PMASA-2016-39/
Duplicate commits 5d427d6 & 80b03a4

**Comment by nijel** [comment]
Thanks for spotting, fixed.
