### ISSUE TITLE
Expired certificate in planet.phpmyadmin.net

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/website#52]
Expired certificate in planet.phpmyadmin.net, details:
```
Subject: planet.phpmyadmin.net
Issuer: Let's Encrypt Authority X3
Expires on: Dec 25, 2016
Current date: Dec 25, 2016
```

**Comment by ibennetch** [comment]
Thanks for reporting this. 

The build script is also throwing an error as a result.

**Comment by nijel** [comment]
Already fixed, the web server didn't pickup renewed certificates.
