### ISSUE TITLE
Missing a link to the Author at themes page

### ISSUE THREAD

**Issue by edwarddekker** [phpmyadmin/website#57]
At the themes page do I missing a direct link from the author who writes the theme. Underneath the author name can we create also a uri.

**Comment by nijel** [comment]
We currently do not have that data, but certainly this is something what should be included with the theme...

**Comment by nijel** [comment]
It is now possible to specify such metadata directly in the theme: https://docs.phpmyadmin.net/en/latest/themes.html#theme-metadata
