### ISSUE TITLE
Replace SHA1 checksums as they 'practically' broken

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/website#59]
The SHA1 hash was practically broken (regarding collision resistance), see:
https://shattered.io/
thus it's not recommended to use it in scenarios that relay on collision resistance.
Regarding PMA it's mean to remove it's usage as checksum for downloads.
(HMAC-SHA1 [cookie auth + github api] is still safe as it's security not depend on resistance to collisions)

fix:
1. remove SHA1 checksums usage for downloadable files in:
https://www.phpmyadmin.net/downloads/
https://www.phpmyadmin.net/themes/
2. optional: add BLAKE2 checksums instead (b2sum tool), more information:
https://www.gnu.org/software/coreutils/manual/html_node/b2sum-invocation.html#b2sum-invocation
https://leastauthority.com/blog/BLAKE2-harder-better-faster-stronger-than-MD5/

SHA256 is considered secure, it's not broken even theoretically.

**Comment by nijel** [comment]
I've removed displaying of SHA1 hashes. It can't be completely removed as it's necessary for composer package list (see https://github.com/composer/composer/issues/5940).

Also I don't think that introducing something else than SHA256 makes sense right now.

**Comment by emanuelb** [comment]
> I've removed displaying of SHA1 hashes.

more places to remove:
https://github.com/phpmyadmin/website/blob/bdea1b42ae4d15d832401ccf0b38eb407005831d/pmaweb/templates/_dlbox.html#L2

https://github.com/phpmyadmin/themes/blob/d77636525be8ff713fa67a3ad48f4e97f9d130ea/create-release.sh#L76
https://github.com/phpmyadmin/themes/blob/d77636525be8ff713fa67a3ad48f4e97f9d130ea/create-release.sh#L97

does all the below instances required for the adding of SHA1 to packages.json ( in composer usage) ?

several mentions in (lines: 38-39, 44)
https://github.com/phpmyadmin/website/blob/f59a3eedbffb721bbe49d71a15886e2e2e12494d/files/management/commands/add_missing_checksums.py#L24

https://github.com/phpmyadmin/website/blob/e00abfb8eb07bcd6afe965b72d0e0a85e387d905/files/models.py#L253
https://github.com/phpmyadmin/website/blob/e00abfb8eb07bcd6afe965b72d0e0a85e387d905/files/models.py#L326
https://github.com/phpmyadmin/website/blob/f59a3eedbffb721bbe49d71a15886e2e2e12494d/files/management/commands/import_files.py#L54
https://github.com/phpmyadmin/website/blob/f59a3eedbffb721bbe49d71a15886e2e2e12494d/files/management/commands/import_themes.py#L59
> It can't be completely removed as it's necessary for composer package list (see composer/composer#5940).

Yeah, they bit slow on the needed work regarding transition to more secure checksums & verification mechanisms :(

> Also I don't think that introducing something else than SHA256 makes sense right now.

agree, thus added it as optional (BLAKE2/SHA-3 are better for new usages, still SHA-256 usage is good from security POV)

**Comment by nijel** [comment]
All the locations in files are needed to ensure everything works with composer (some of them cover corner cases which probably won't happen). I've kept the same code on themes as well right now to have consistent code for both files and themes. It's not used there, but IMHO it's better from maintenance perspective.

As for adding another checksums, I'd prefer to wait until either of these is widely used, what doesn't seem to be case for neither of them right now (in the end we need something people know and will use).

**Comment by emanuelb** [comment]
> As for adding another checksums, I'd prefer to wait until either of these is widely used, what doesn't seem to be case for neither of them right now (in the end we need something people know and will use).

agree, and using sha-256 is totally fine, even if sha-3/blake2 is better (and has the related tools in coreutils as well) :)
