### ISSUE TITLE
missing credit in PMASA-2017-5 in References

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/website#60]
in:
https://www.phpmyadmin.net/security/PMASA-2017-5/
it's missing credit in "References" section.

fix:
Add credit as in PMASA-2017-4 to PMASA-2017-5
> Thanks to Emanuel Bronshtein @e3amn2l for reporting this vulnerability.

**Comment by nijel** [comment]
Sorry for missing that, fixed now.
