### ISSUE TITLE
redirection status codes

### ISSUE THREAD

**Issue by BO41** [phpmyadmin/website#78]
there are more than 29 pages linked with a redirect returning a status code between 300 and 399.

and also 1 page with a 4xx code.

fixing this would improve the website overall

**Comment by nijel** [comment]
Listing the problematic pages you have found would be helpful :-)

**Comment by BO41** [comment]
for some reason I am not able to upload files :(
(the lists are automatically generated)

this is a list of connection errors
https://pastebin.com/5N7siy1k

here are broken urls
https://pastebin.com/0wWeEn1u

and here some 3xx redirects
https://pastebin.com/yUhBLsHC

the 4xx was a unauthorized, so sorry for mentioning it

**Comment by nijel** [comment]
I can't reproduce the errors on files.phpmyadmin.net, maybe you just did the test too aggressively and the CDN did apply some kind of DOS protection against you...

**Comment by BO41** [comment]
this is totally an option. never tested sites with a CDN.

then just look through the list and if you don't see a problem just close this issue and forget it :)
