### ISSUE TITLE
Wrong link to a book

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/website#79]
Received by email:

> https://www.phpmyadmin.net/  links to https://link.packtpub.com/XJdqZr for the "Mastering phpMyAdmin 3.4 for Effective MySQL Management” book, but for me, that shortened link resolves to "Moodle 2 Administration” (https://www.packtpub.com/hardware-and-creative/moodle-2-administration) instead of https://www.packtpub.com/big-data-and-business-intelligence/mastering-phpmyadmin-34-effective-mysql-management. 
> I’m guessing it’s a typo, or packtpub’s link shortener has gone funny.

**Comment by nijel** [comment]
The link is same from 97abdf13, so I guess they have changed it. Maybe @lem9 has still some contacts there to investigate this?

**Comment by ibennetch** [comment]
I fixed this by adjusting the links to the long form URL which seems to be pretty stable.

**Comment by lem9** [comment]
Thanks Michal and Isaac.
